### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Daanvdplas** [use-ink/drink#122]
Who can I contact regarding drink?

**Comment by pmikolajczyk41** [comment]
I guess that would be me :)

**Comment by Daanvdplas** [comment]
I'm trying to test the examples but I can't seem to run them:

<img width="1415" alt="Screenshot 2024-08-08 at 20 16 41" src="https://github.com/user-attachments/assets/aa9b8665-7fff-4025-a1a6-e69717c4d71e">
```
Blocking waiting for file lock on build directory
```

I tried a different branch and it worked but on main all the examples get stuck.

Should drink work with ink! v5?

**Comment by pmikolajczyk41** [comment]
Please try with `--release`

**Comment by Daanvdplas** [comment]
That worked. Any idea what this could be: 

<img width="1408" alt="Screenshot 2024-08-09 at 10 03 21" src="https://github.com/user-attachments/assets/d9f95898-d933-459a-b26c-e6205ce42882">

My Cargo.toml:
```
[package]
name = "api_example"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }
pop-api = { path = "../pop-node/pop-api", default-features = false, features = ["fungibles"] }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
drink = "0.8"

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "pop-api/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []

```

**Comment by Daanvdplas** [comment]
It could have something to do with the repo using an older `cargo contract`?

**Comment by Daanvdplas** [comment]
Working
