### ISSUE TITLE
`session.call` with parameter is a `Vec<u8>`

### ISSUE THREAD

**Issue by chungquantin** [use-ink/drink#125]
The method `call()` of `session` expected the parameters to be `AsRef<str>`. Wonder how a contract method that accepts the `Vec<u8>` can be called using `drink`?

**Comment by pmikolajczyk41** [comment]
`Vec<u8>` can be accepted - it has just to be passed as a string literal, in the same form as it would have been passed to the `cargo contract` (it must meet the format required by SCALE)
