### ISSUE TITLE
Copying the output from TUI

### ISSUE THREAD

**Issue by pmikolajczyk41** [use-ink/drink#6]
cc: @JoshOrndorff

**Comment by pmikolajczyk41** [comment]
it seems that there is no way of universal support for selecting text from the TUI:
![image](https://github.com/Cardinal-Cryptography/drink/assets/27450471/01f429d6-4382-47ff-a93e-abbf542195cd)

but following the Reddit suggestion:
https://www.reddit.com/r/rust/comments/13ngl6r/comment/jl04apc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I am able to copy whatever I need by holding `Shift` key and selecting text with my mouse (I'm on Ubuntu with bash / fish). Is this sufficient for now @JoshOrndorff ?

**Comment by JoshOrndorff** [comment]
Indeed! Holding shift allows me to copy! Thanks reddit and @pmikolajczyk4
